export type Cmd =
  | "get_lang"
  | "set_lang"
  | "get_language_resource_bundle"
  | "download_tool"
  | "get_tools_download_dir"
  | "get_tools_manifest"
  | "get_tools_install_state"
  | "runtime_host_platform"
  | "get_tool_executable_path"
  | "open_tool_executable"
  | "log_fe"
  | "log_fe_req"
  | "open_modal_window"
  | "close_modal_window"
  | "get_app_session";
